version: 2

exposures:  
  - name: Greenery Product Funnel Dashboard
    description: >
      Models that are critical to our product funnel dashboard
    type: dashboard
    maturity: high
    owner:
      name: Etisha Pathak
      email: epathak@ucsc.edu
    depends_on:
      - ref('int_session_events')
      - ref('conversion_rate')
